-- RagDay27 canonical registrations database contract
-- Supabase project ref: xulkacnjqjnluhmbqbcu
-- Single sequential registration series across all genders: RD27-01, RD27-02, ... RD27-100, etc.
-- Reset rule: When registrations table contains zero records, restart numbering from SL No = 1, Registration No = RD27-01.
-- Non-empty rule: Continue sequential numbering without reusing deleted numbers.

create extension if not exists pgcrypto;

-- 1. REGISTRATIONS TABLE
create table if not exists public.registrations (
  id uuid primary key default gen_random_uuid(),
  sl_no bigint generated by default as identity unique,
  registration_no text not null unique,
  full_name text not null,
  class_roll text not null,
  student_id text not null,
  contact_mobile_number text not null,
  academic_group text not null,
  academic_section text not null,
  student_photo text,
  send_method text not null check (lower(send_method) in ('bkash','nagad')),
  sender_mobile_no text not null,
  payment_time text not null,
  transaction_id text,
  jersey_back_name varchar(14) not null,
  jersey_number varchar(2) not null check (jersey_number ~ '^[0-9]{2}$'),
  jersey_size text not null check (jersey_size in ('S','M','L','XL','2XL','3XL','4XL')),
  gender text not null check (gender in ('male','female')),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  reject_reason text,
  approved_by uuid references public.admins(id),
  rejected_by uuid references public.admins(id),
  approved_at timestamptz,
  rejected_at timestamptz,
  hidden_from_web boolean not null default false,
  hidden_by uuid references public.admins(id),
  hidden_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Ensure sl_no allows inserting calculated numbers (fixes error 428C9 if defined as GENERATED ALWAYS)
alter table public.registrations alter column sl_no set generated by default;

create index if not exists idx_registrations_student_id on public.registrations(student_id);
create index if not exists idx_registrations_class_roll on public.registrations(class_roll);
create index if not exists idx_registrations_gender_status on public.registrations(gender,status);
create index if not exists idx_registrations_approved_by on public.registrations(approved_by);
create index if not exists idx_registrations_rejected_by on public.registrations(rejected_by);
create index if not exists idx_registrations_hidden_by on public.registrations(hidden_by);
create index if not exists idx_registrations_hidden_gender_status on public.registrations(hidden_from_web,gender,status);

-- Enable Row Level Security
alter table public.registrations enable row level security;

-- Supabase permissions: Direct table access is restricted. Public access occurs strictly via RPCs.
grant usage on schema public to anon, authenticated, service_role;
revoke all on table public.registrations from anon;
grant select, insert, update, delete on table public.registrations to authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

-- Realtime publication
do $$
begin
  alter publication supabase_realtime add table public.registrations;
exception when duplicate_object then null;
end $$;

-- 2. SEQUENCE ALLOCATOR & EMPTY DATABASE NUMBER RESET
create or replace function public.get_next_registration_number()
returns table (next_sl_no bigint, next_registration_no text)
language plpgsql
security definer
as $$
declare
  v_count bigint;
  v_max_num bigint := 0;
  v_rec record;
begin
  select count(*) into v_count from public.registrations;
  if v_count = 0 then
    -- Table is completely empty: restart from 1 and RD27-01
    return query select 1::bigint, 'RD27-01'::text;
    return;
  end if;

  -- Table is NOT empty: find the maximum sequence allocated so far without reusing deleted numbers
  for v_rec in select registration_no, sl_no from public.registrations loop
    if v_rec.registration_no ~ '0*([0-9]+)$' then
      v_max_num := greatest(v_max_num, (regexp_matches(v_rec.registration_no, '0*([0-9]+)$'))[1]::bigint);
    end if;
    if v_rec.sl_no is not null then
      v_max_num := greatest(v_max_num, v_rec.sl_no);
    end if;
  end loop;

  v_max_num := v_max_num + 1;
  return query select v_max_num, ('RD27-' || case when v_max_num < 10 then '0' || v_max_num::text else v_max_num::text end);
end;
$$;

-- 3. VERIFY ADMIN PASSCODE
create or replace function public.verify_admin_passcode(p_passcode text)
returns json
language plpgsql
security definer
as $$
declare
  clean_pass text := trim(coalesce(p_passcode, ''));
begin
  if clean_pass = 'nic27.boy' or clean_pass = 'nicboy.27' then
    return json_build_object('role', 'male_admin', 'admin_id', 'male-admin');
  elsif clean_pass = 'nic27.girl' then
    return json_build_object('role', 'female_admin', 'admin_id', 'female-admin');
  else
    return null;
  end if;
end;
$$;

-- 4. GET ADMIN REGISTRATIONS (GENDER-SCOPED DIRECT DATABASE ACCESS)
create or replace function public.get_admin_registrations(p_passcode text)
returns setof public.registrations
language plpgsql
security definer
as $$
declare
  clean_pass text := trim(coalesce(p_passcode, ''));
begin
  if clean_pass = 'nic27.boy' or clean_pass = 'nicboy.27' then
    return query
      select * from public.registrations
      where gender = 'male' and hidden_from_web = false
      order by sl_no desc;
  elsif clean_pass = 'nic27.girl' then
    return query
      select * from public.registrations
      where gender = 'female' and hidden_from_web = false
      order by sl_no desc;
  else
    raise exception 'unauthorized: invalid admin passcode' using errcode = '42501';
  end if;
end;
$$;

-- 5. CREATE REGISTRATION
create or replace function public.create_registration(
  p_full_name text,
  p_class_roll text,
  p_student_id text,
  p_contact_mobile_number text,
  p_academic_group text,
  p_academic_section text,
  p_student_photo text,
  p_send_method text,
  p_sender_mobile_no text,
  p_payment_time text,
  p_transaction_id text,
  p_jersey_back_name text,
  p_jersey_number text,
  p_jersey_size text,
  p_gender text
)
returns public.registrations
language plpgsql
security definer
as $$
declare
  v_next record;
  v_new_reg public.registrations;
begin
  select next_sl_no, next_registration_no into v_next from public.get_next_registration_number();

  insert into public.registrations (
    sl_no,
    registration_no,
    full_name,
    class_roll,
    student_id,
    contact_mobile_number,
    academic_group,
    academic_section,
    student_photo,
    send_method,
    sender_mobile_no,
    payment_time,
    transaction_id,
    jersey_back_name,
    jersey_number,
    jersey_size,
    gender,
    status
  ) overriding system value values (
    v_next.next_sl_no,
    v_next.next_registration_no,
    trim(p_full_name),
    trim(p_class_roll),
    trim(p_student_id),
    trim(p_contact_mobile_number),
    trim(p_academic_group),
    trim(p_academic_section),
    p_student_photo,
    trim(p_send_method),
    trim(p_sender_mobile_no),
    trim(p_payment_time),
    nullif(trim(p_transaction_id), ''),
    trim(p_jersey_back_name),
    trim(p_jersey_number),
    trim(p_jersey_size),
    trim(p_gender),
    'pending'
  ) returning * into v_new_reg;

  return v_new_reg;
end;
$$;

-- 6. APPROVE REGISTRATION
create or replace function public.approve_registration(
  p_passcode text,
  p_registration_no text
)
returns public.registrations
language plpgsql
security definer
as $$
declare
  clean_pass text := trim(coalesce(p_passcode, ''));
  clean_reg_no text := upper(trim(coalesce(p_registration_no, '')));
  v_admin_role text;
  v_admin_id uuid;
  v_reg public.registrations;
begin
  if clean_pass = 'nic27.boy' or clean_pass = 'nicboy.27' then
    v_admin_role := 'male_admin';
  elsif clean_pass = 'nic27.girl' then
    v_admin_role := 'female_admin';
  else
    raise exception 'unauthorized: invalid admin passcode' using errcode = '42501';
  end if;

  select id into v_admin_id from public.admins where role = v_admin_role limit 1;
  if v_admin_id is null then
    v_admin_id := case when v_admin_role = 'male_admin' then '11111111-1111-1111-1111-111111111111'::uuid else '22222222-2222-2222-2222-222222222222'::uuid end;
  end if;

  select * into v_reg from public.registrations where upper(registration_no) = clean_reg_no;
  if not found then
    raise exception 'REGISTRATION_NOT_FOUND' using errcode = 'P0002';
  end if;

  if (v_admin_role = 'male_admin' and v_reg.gender <> 'male') or
     (v_admin_role = 'female_admin' and v_reg.gender <> 'female') then
    raise exception 'GENDER_ROLE_MISMATCH' using errcode = '42501';
  end if;

  update public.registrations
  set status = 'approved',
      approved_by = v_admin_id,
      approved_at = now(),
      reject_reason = null,
      updated_at = now()
  where id = v_reg.id
  returning * into v_reg;

  return v_reg;
end;
$$;

-- 7. REJECT REGISTRATION
create or replace function public.reject_registration(
  p_passcode text,
  p_registration_no text,
  p_reason text
)
returns public.registrations
language plpgsql
security definer
as $$
declare
  clean_pass text := trim(coalesce(p_passcode, ''));
  clean_reg_no text := upper(trim(coalesce(p_registration_no, '')));
  clean_reason text := trim(coalesce(p_reason, ''));
  v_admin_role text;
  v_admin_id uuid;
  v_reg public.registrations;
begin
  if clean_pass = 'nic27.boy' or clean_pass = 'nicboy.27' then
    v_admin_role := 'male_admin';
  elsif clean_pass = 'nic27.girl' then
    v_admin_role := 'female_admin';
  else
    raise exception 'unauthorized: invalid admin passcode' using errcode = '42501';
  end if;

  if clean_reason = '' then
    raise exception 'REJECTION_REASON_REQUIRED' using errcode = '22023';
  end if;

  select id into v_admin_id from public.admins where role = v_admin_role limit 1;
  if v_admin_id is null then
    v_admin_id := case when v_admin_role = 'male_admin' then '11111111-1111-1111-1111-111111111111'::uuid else '22222222-2222-2222-2222-222222222222'::uuid end;
  end if;

  select * into v_reg from public.registrations where upper(registration_no) = clean_reg_no;
  if not found then
    raise exception 'REGISTRATION_NOT_FOUND' using errcode = 'P0002';
  end if;

  if (v_admin_role = 'male_admin' and v_reg.gender <> 'male') or
     (v_admin_role = 'female_admin' and v_reg.gender <> 'female') then
    raise exception 'GENDER_ROLE_MISMATCH' using errcode = '42501';
  end if;

  update public.registrations
  set status = 'rejected',
      reject_reason = clean_reason,
      rejected_by = v_admin_id,
      rejected_at = now(),
      updated_at = now()
  where id = v_reg.id
  returning * into v_reg;

  return v_reg;
end;
$$;

-- 8. HIDE REGISTRATION FROM WEB
create or replace function public.hide_registration_from_web(
  p_passcode text,
  p_registration_no text
)
returns public.registrations
language plpgsql
security definer
as $$
declare
  clean_pass text := trim(coalesce(p_passcode, ''));
  clean_reg_no text := upper(trim(coalesce(p_registration_no, '')));
  v_admin_role text;
  v_admin_id uuid;
  v_reg public.registrations;
begin
  if clean_pass = 'nic27.boy' or clean_pass = 'nicboy.27' then
    v_admin_role := 'male_admin';
  elsif clean_pass = 'nic27.girl' then
    v_admin_role := 'female_admin';
  else
    raise exception 'unauthorized: invalid admin passcode' using errcode = '42501';
  end if;

  select id into v_admin_id from public.admins where role = v_admin_role limit 1;
  if v_admin_id is null then
    v_admin_id := case when v_admin_role = 'male_admin' then '11111111-1111-1111-1111-111111111111'::uuid else '22222222-2222-2222-2222-222222222222'::uuid end;
  end if;

  select * into v_reg from public.registrations where upper(registration_no) = clean_reg_no;
  if not found then
    raise exception 'REGISTRATION_NOT_FOUND' using errcode = 'P0002';
  end if;

  if (v_admin_role = 'male_admin' and v_reg.gender <> 'male') or
     (v_admin_role = 'female_admin' and v_reg.gender <> 'female') then
    raise exception 'GENDER_ROLE_MISMATCH' using errcode = '42501';
  end if;

  update public.registrations
  set hidden_from_web = true,
      hidden_by = v_admin_id,
      hidden_at = now(),
      updated_at = now()
  where id = v_reg.id
  returning * into v_reg;

  return v_reg;
end;
$$;

-- 9. FIND REGISTRATION DUPLICATE
create or replace function public.find_registration_duplicate(
  p_student_id text,
  p_full_name text,
  p_class_roll text,
  p_academic_group text,
  p_academic_section text
)
returns setof public.registrations
language plpgsql
security definer
as $$
begin
  return query
    select * from public.registrations
    where hidden_from_web = false
      and (
        student_id = trim(p_student_id)
        or (lower(trim(full_name)) = lower(trim(p_full_name)) and class_roll = trim(p_class_roll))
      )
    limit 1;
end;
$$;

-- 10. RESUBMIT REJECTED REGISTRATION
create or replace function public.resubmit_rejected_registration(
  p_registration_id uuid,
  p_original_student_id text,
  p_original_full_name text,
  p_original_class_roll text,
  p_original_academic_group text,
  p_original_academic_section text,
  p_full_name text,
  p_class_roll text,
  p_student_id text,
  p_contact_mobile_number text,
  p_academic_group text,
  p_academic_section text,
  p_student_photo text,
  p_send_method text,
  p_sender_mobile_no text,
  p_payment_time text,
  p_transaction_id text,
  p_jersey_back_name text,
  p_jersey_number text,
  p_jersey_size text,
  p_gender text
)
returns public.registrations
language plpgsql
security definer
as $$
declare
  v_reg public.registrations;
begin
  select * into v_reg from public.registrations where id = p_registration_id and status = 'rejected';
  if not found then
    raise exception 'REJECTED_REGISTRATION_NOT_FOUND' using errcode = 'P0001';
  end if;

  update public.registrations
  set full_name = trim(p_full_name),
      class_roll = trim(p_class_roll),
      student_id = trim(p_student_id),
      contact_mobile_number = trim(p_contact_mobile_number),
      academic_group = trim(p_academic_group),
      academic_section = trim(p_academic_section),
      student_photo = coalesce(p_student_photo, student_photo),
      send_method = trim(p_send_method),
      sender_mobile_no = trim(p_sender_mobile_no),
      payment_time = trim(p_payment_time),
      transaction_id = nullif(trim(p_transaction_id), ''),
      jersey_back_name = trim(p_jersey_back_name),
      jersey_number = trim(p_jersey_number),
      jersey_size = trim(p_jersey_size),
      gender = trim(p_gender),
      status = 'pending',
      reject_reason = null,
      rejected_at = null,
      rejected_by = null,
      updated_at = now()
  where id = p_registration_id
  returning * into v_reg;

  return v_reg;
end;
$$;

-- 11. LOOKUP INVITATION CARD (PUBLIC SAFE RPC)
create or replace function public.lookup_invitation_card(
  p_registration_no text,
  p_student_name text default null
)
returns json
language plpgsql
security definer
as $$
declare
  clean_reg text := upper(trim(coalesce(p_registration_no, '')));
  r record;
begin
  select * into r from public.registrations
  where upper(registration_no) = clean_reg
  limit 1;

  if not found or r.hidden_from_web = true then
    return json_build_object('found', false, 'status', 'hidden_or_not_found', 'can_download', false);
  end if;

  if r.status = 'pending' then
    return json_build_object(
      'found', true,
      'status', 'pending',
      'can_download', false,
      'registration_no', r.registration_no,
      'full_name', r.full_name
    );
  elsif r.status = 'rejected' then
    return json_build_object(
      'found', true,
      'status', 'rejected',
      'can_download', false,
      'registration_no', r.registration_no,
      'full_name', r.full_name,
      'reject_reason', r.reject_reason,
      'rejected_at', r.rejected_at
    );
  else
    return json_build_object(
      'found', true,
      'status', 'approved',
      'can_download', true,
      'id', r.id,
      'sl_no', r.sl_no,
      'registration_no', r.registration_no,
      'full_name', r.full_name,
      'class_roll', r.class_roll,
      'student_id', r.student_id,
      'contact_mobile_number', r.contact_mobile_number,
      'academic_group', r.academic_group,
      'academic_section', r.academic_section,
      'student_photo', r.student_photo,
      'send_method', r.send_method,
      'sender_mobile_no', r.sender_mobile_no,
      'payment_time', r.payment_time,
      'transaction_id', r.transaction_id,
      'jersey_back_name', r.jersey_back_name,
      'jersey_number', r.jersey_number,
      'jersey_size', r.jersey_size,
      'gender', r.gender,
      'approved_at', r.approved_at,
      'created_at', r.created_at,
      'updated_at', r.updated_at
    );
  end if;
end;
$$;

-- 12. GRANT EXECUTE PRIVILEGES ON ALL RPC FUNCTIONS
grant execute on function public.get_next_registration_number to anon, authenticated, service_role;
grant execute on function public.verify_admin_passcode to anon, authenticated, service_role;
grant execute on function public.get_admin_registrations to anon, authenticated, service_role;
grant execute on function public.create_registration to anon, authenticated, service_role;
grant execute on function public.approve_registration to anon, authenticated, service_role;
grant execute on function public.reject_registration to anon, authenticated, service_role;
grant execute on function public.hide_registration_from_web to anon, authenticated, service_role;
grant execute on function public.find_registration_duplicate to anon, authenticated, service_role;
grant execute on function public.resubmit_rejected_registration to anon, authenticated, service_role;
grant execute on function public.lookup_invitation_card to anon, authenticated, service_role;
