-- RagDay27 canonical registrations database contract
-- Supabase project ref: xulkacnjqjnluhmbqbcu
-- Single sequential registration series across all genders: RD27-01, RD27-02, ... RD27-100, etc.
-- Reset rule: When registrations table contains zero records, restart numbering from SL No = 1, Registration No = RD27-01.
-- Non-empty rule: Continue sequential numbering without reusing deleted numbers.

create extension if not exists pgcrypto;

create table if not exists public.registrations (
  id uuid primary key default gen_random_uuid(),
  sl_no bigint generated by default as identity unique,
  registration_no text not null unique,
  full_name text not null,
  class_roll text not null,
  student_id text not null,
  contact_mobile_number text not null,
  academic_group text not null,
  academic_section text not null,
  student_photo text,
  send_method text not null check (lower(send_method) in ('bkash','nagad')),
  sender_mobile_no text not null,
  payment_time text not null,
  transaction_id text,
  jersey_back_name varchar(14) not null,
  jersey_number varchar(2) not null check (jersey_number ~ '^[0-9]{2}$'),
  jersey_size text not null check (jersey_size in ('S','M','L','XL','2XL','3XL','4XL')),
  gender text not null check (gender in ('male','female')),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  reject_reason text,
  approved_by uuid references public.admins(id),
  rejected_by uuid references public.admins(id),
  approved_at timestamptz,
  rejected_at timestamptz,
  hidden_from_web boolean not null default false,
  hidden_by uuid references public.admins(id),
  hidden_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_registrations_student_id on public.registrations(student_id);
create index if not exists idx_registrations_class_roll on public.registrations(class_roll);
create index if not exists idx_registrations_gender_status on public.registrations(gender,status);
create index if not exists idx_registrations_approved_by on public.registrations(approved_by);
create index if not exists idx_registrations_rejected_by on public.registrations(rejected_by);
create index if not exists idx_registrations_hidden_by on public.registrations(hidden_by);
create index if not exists idx_registrations_hidden_gender_status on public.registrations(hidden_from_web,gender,status);

-- Enable Row Level Security
alter table public.registrations enable row level security;

-- Supabase permissions: Grant table and schema privileges
grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on table public.registrations to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

-- Row Level Security (RLS) Policies
drop policy if exists "Allow public select registrations" on public.registrations;
create policy "Allow public select registrations"
  on public.registrations
  for select
  to anon, authenticated, service_role
  using (true);

drop policy if exists "Allow public insert registrations" on public.registrations;
create policy "Allow public insert registrations"
  on public.registrations
  for insert
  to anon, authenticated, service_role
  with check (true);

drop policy if exists "Allow public update registrations" on public.registrations;
create policy "Allow public update registrations"
  on public.registrations
  for update
  to anon, authenticated, service_role
  using (true)
  with check (true);

drop policy if exists "Allow public delete registrations" on public.registrations;
create policy "Allow public delete registrations"
  on public.registrations
  for delete
  to anon, authenticated, service_role
  using (true);

-- Realtime publication
do $$
begin
  alter publication supabase_realtime add table public.registrations;
exception when duplicate_object then null;
end $$;

-- Sequence allocator & empty database reset logic
create or replace function public.get_next_registration_number()
returns table (next_sl_no bigint, next_registration_no text)
language plpgsql
security definer
as $$
declare
  v_count bigint;
  v_max_num bigint := 0;
  v_rec record;
begin
  select count(*) into v_count from public.registrations;
  if v_count = 0 then
    -- Table is completely empty: restart from 1 and RD27-01
    return query select 1::bigint, 'RD27-01'::text;
    return;
  end if;

  -- Table is NOT empty: find the maximum sequence allocated so far without reusing deleted numbers
  for v_rec in select registration_no, sl_no from public.registrations loop
    if v_rec.registration_no ~ '0*([0-9]+)$' then
      v_max_num := greatest(v_max_num, (regexp_matches(v_rec.registration_no, '0*([0-9]+)$'))[1]::bigint);
    end if;
    if v_rec.sl_no is not null then
      v_max_num := greatest(v_max_num, v_rec.sl_no);
    end if;
  end loop;

  v_max_num := v_max_num + 1;
  return query select v_max_num, ('RD27-' || case when v_max_num < 10 then '0' || v_max_num::text else v_max_num::text end);
end;
$$;

-- Grant execute privileges on RPC functions
grant execute on function public.get_next_registration_number to anon, authenticated, service_role;
grant execute on function public.get_admin_registrations to anon, authenticated, service_role;
grant execute on function public.verify_admin_passcode to anon, authenticated, service_role;
grant execute on function public.approve_registration to anon, authenticated, service_role;
grant execute on function public.reject_registration to anon, authenticated, service_role;
grant execute on function public.hide_registration_from_web to anon, authenticated, service_role;
grant execute on function public.create_registration to anon, authenticated, service_role;
grant execute on function public.resubmit_rejected_registration to anon, authenticated, service_role;
grant execute on function public.find_registration_duplicate to anon, authenticated, service_role;
grant execute on function public.lookup_invitation_card to anon, authenticated, service_role;
